
apiVersion: k3d.io/v1alpha2
kind: Simple
name: podra
servers: 1
agents: 2
image: docker.io/rancher/k3s:v1.21.1-k3s1
volumes:
  - volume: data:/tmp/data
    nodeFilters:
      - agent[*]
labels:
  - label: node=worker1
    nodeFilters:
      - agent[0]
  - label: node=worker2
    nodeFilters:
      - agent[1]
