apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.logs.name }}
  namespace: airflow
  labels:
    app: {{ .Values.logs.name }}
spec:
  storageClassName: manual
  capacity:
    storage: {{ .Values.logs.size }}
  accessModes:
    - ReadWriteMany
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: {{ .Values.logs.name }}
    namespace: airflow
  hostPath:
    path: /tmp/data
