apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.logs.name }}
  labels:
    app: {{ .Values.logs.name }}
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.logs.size }}
