blank_lines_upper_bound = 2
combine_control_expr = false
condense_wildcard_suffixes = true
edition = "2021"
enum_discrim_align_threshold = 20
error_on_line_overflow = true
error_on_unformatted = true
fn_args_layout = "Vertical"
fn_single_line = true
format_strings = true
group_imports = "StdExternalCrate"
imports_layout = "HorizontalVertical"
imports_granularity = "Crate"
match_block_trailing_comma = true
max_width = 80
normalize_comments = true
overflow_delimited_expr = true
reorder_impl_items = true
struct_field_align_threshold = 20
use_field_init_shorthand = true
version = "Two"
wrap_comments = true