
airflow:
  defaultAirflowRepository: podra/orchestrator
  defaultAirflowTag: "latest"
  airflowVersion: "2.1.3"
  executor: "KubernetesExecutor"
  logs:
    persistence:
      enabled: true
      existingClaim: orchestrator-logs

logs:
  size: 1Mi
  name: orchestrator-logs