spring:
  kafka:
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        '[spring.json.type.mapping]': post:com.podra.types.Post,comment:com.podra.types.Comment
    consumer:
      enable-auto-commit: false
      auto-offset-reset: earliest
      group-id: com.podra
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
    listener:
      ack-mode: RECORD